I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 257, in script
    with easein
  File "game/script.rpy", line 257, in <module>
    with easein
NameError: name 'easein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 257, in script
    with easein
  File "C:\renpy-8.3.2-sdk\renpy\ast.py", line 1354, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 257, in <module>
    with easein
NameError: name 'easein' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Tech Demo 1.0
Tue Nov 26 12:42:52 2024
